trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: |
    pip install -r requirements.txt
    pytest --maxfail=1 --disable-warnings -q
  displayName: 'Run Tests'
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: 'alumicatalyst/app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
