apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumicatalyst-deployment
  labels:
    app: alumicatalyst
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alumicatalyst
  template:
    metadata:
      labels:
        app: alumicatalyst
    spec:
      containers:
      - name: alumicatalyst
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
